/**
 * Generates apps/admin/src/tokens.generated.css from @tpa/theme — the SINGLE
 * source of truth. Do not hand-edit the output. Regenerate with:
 *
 *   pnpm --filter admin generate:tokens
 *
 * Colors emit as-is (hex/rgba). Unitless numeric scales (spacing/radii/type)
 * emit as px, except font weights which stay unitless. Tint/expiry pairs and an
 * elevation shadow are flattened to individual properties.
 */
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import { tokens } from '@tpa/theme';

const here = dirname(fileURLToPath(import.meta.url));
const outPath = join(here, '..', 'src', 'tokens.generated.css');

const lines: string[] = [];
const push = (name: string, value: string | number) => lines.push(`  --${name}: ${value};`);
const px = (n: number) => `${n}px`;

// Colors (nested object of strings) -> --color-<path>
function walkColors(obj: Record<string, unknown>, prefix: string) {
  for (const [key, val] of Object.entries(obj)) {
    const name = `${prefix}-${key}`;
    if (typeof val === 'string') push(name, val);
    else if (val && typeof val === 'object') walkColors(val as Record<string, unknown>, name);
  }
}

walkColors(tokens.color as unknown as Record<string, unknown>, 'color');

// Domain tint pairs
for (const [type, pair] of Object.entries(tokens.trainingTint)) {
  push(`training-${type}-fg`, pair.fg);
  push(`training-${type}-bg`, pair.bg);
}
for (const [state, pair] of Object.entries(tokens.creditExpiry)) {
  push(`expiry-${state}-fg`, pair.fg);
  push(`expiry-${state}-bg`, pair.bg);
}

// Numeric scales
for (const [k, v] of Object.entries(tokens.space)) push(`space-${k}`, px(v));
for (const [k, v] of Object.entries(tokens.radius)) push(`radius-${k}`, px(v));
for (const [k, v] of Object.entries(tokens.fontSize)) push(`font-size-${k}`, px(v));
for (const [k, v] of Object.entries(tokens.lineHeight)) push(`line-height-${k}`, px(v));
for (const [k, v] of Object.entries(tokens.letterSpacing)) push(`letter-spacing-${k}`, px(v));
for (const [k, v] of Object.entries(tokens.fontWeight)) push(`font-weight-${k}`, v);

// One elevation shadow (md) as a ready-to-use box-shadow.
const e = tokens.elevation.md;
push('shadow-md', `0 ${px(e.y)} ${px(e.blur)} rgba(7,16,31,${e.opacity})`);

const css = `/* GENERATED by scripts/generate-tokens.ts from @tpa/theme. Do not edit by hand. */\n:root {\n${lines.join('\n')}\n}\n`;

writeFileSync(outPath, css);
console.log(`Wrote ${outPath} (${lines.length} custom properties)`);
