import type { Brand } from './brand';

/**
 * Every entity id is a text id supplied by the INSERT code — the database has
 * NO default. (A previous project hit repeated 23502 not-null violations by
 * relying on a DB default that wasn't there.) Ids are generated by `newId` in
 * @tpa/core, which prefixes them per entity, e.g. `pl_9f3a...`.
 *
 * Each id is branded so the compiler rejects passing a PlayerId where a CoachId
 * is expected. The textual prefix (`pl_`, `co_`, ...) is a runtime convention
 * enforced in @tpa/core (see ID_PREFIXES); the brand here is the compile-time half.
 */
export type PlayerId = Brand<string, 'PlayerId'>; //                pl_
export type CoachId = Brand<string, 'CoachId'>; //                  co_
export type PackageId = Brand<string, 'PackageId'>; //              pk_
export type PurchaseId = Brand<string, 'PurchaseId'>; //           pu_
export type CreditBatchId = Brand<string, 'CreditBatchId'>; //      cb_
export type SlotId = Brand<string, 'SlotId'>; //                    sl_
export type BookingId = Brand<string, 'BookingId'>; //             bk_
export type AvailabilityTemplateId = Brand<string, 'AvailabilityTemplateId'>; // at_
export type NotificationId = Brand<string, 'NotificationId'>; //    nt_
export type DeviceTokenId = Brand<string, 'DeviceTokenId'>; //      dpt_
